### ISSUE TITLE
What does the event_class member mean in bmc_data?

### ISSUE THREAD

**Issue by nrwahl2** [power-ras/libservicelog#2]
I don't see it documented anywhere and don't see any relevant functions in the OpenIPMI headers. The people who wrote a tool I'm updating couldn't figure it out either, and they set it to 0.

**Comment by maheshsal** [comment]
It is decade old code and not in use since servicelog is no more supported on PowerNV platform. I guess the event class was introduced to classify event sensor class (e.g. Threshold, discrete and OEM class). However, I don't see any values defined for the same in libservicelog header files and no documentation whatsoever. Hence, I don't see any harm in setting it to 0 or ignore it completely.

**Comment by nrwahl2** [comment]
Thanks @maheshsal. My team was looking into fixing some issues in some also-decade-old code that used libservicelog, and I came across this in the process. We decided to retire it since there are no known users, and it sounds like we made the right call :)
